# server configuration
# defaults used by Github Pages
destination: ./_site
lsi: false
pygments: true
safe: true
source: .
# my own overrides
# auto: true    # deprecated
markdown: maruku
permalink: /:year/:month/:day/:title.html
