# server configuration
# defaults used by Github Pages
destination: ./_site
lsi: false
highlighter: rouge
safe: true
source: .
# my own overrides
# auto: true    # deprecated
markdown: kramdown
permalink: /:year/:month/:day/:title.html
